apiVersion: warehouse/v1alpha1
kind: Component
metadata:
  name: Asset-WH-400
  description: |
    An asset from Warehouse team.
  links:
    - title: Website
      url: https://inside-docupedia.bosch.com/confluence2/pages/viewpage.action?pageId=460129541
    - title: Documentation
      url: https://github.com/ktx2kor/Backstage_test/blob/main/README.md
    - title: Code Repository
      url: https://github.com/ktx2kor/Backstage_test/
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: service
  system: backstage-playgroup
  owner: PMT
  lifecycle: experimental
  consumesApis:
    - csi-deployer
  implementsApis:
    - csi-intregation
  source:
    type: git
    target: https://github.com/ktx2kor/Backstage_test.git
    branch: bdc-develop
