apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Asset-WH-2
  description: |
    An asset 2 from Warehouse team.
  links:
    - title: Website
      url: https://inside-docupedia.bosch.com/confluence2/pages/viewpage.action?pageId=460129541
    - title: Documentation
      url: https://github.com/ktx2kor/Backstage_test/blob/main/README.md
    - title: Code Repository
      url: https://github.com/ktx2kor/Backstage_test/
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: service
  system: backstage-playgroup
  owner: PMT
  lifecycle: experimental
  definition: "openapi: 3.0.0\ninfo:\n  title: Asset Management API\n  version: 1.0.0\n  description: API to manage asset information\n\nservers:\n  - url: http://localhost:5000\n    description: Local development server\n\npaths:\n  /assets:\n    post:\n      summary: Create a new asset\n      operationId: createAsset\n      tags:\n        - Asset\n      requestBody:\n        required: true\n        content:\n          application/json:\n            schema:\n              $ref: '#/components/schemas/Asset'\n      responses:\n        '201':\n          description: Asset created successfully\n          content:\n            application/json:\n              schema:\n                $ref: '#/components/schemas/Asset'\n        '400':\n          description: Bad request\n        '500':\n          description: Internal server error\n\n  /assets/{id}:\n    get:\n      summary: Get an asset by ID\n      operationId: getAssetById\n      tags:\n        - Asset\n      parameters:\n        - name: id\n          in: path\n          required: true\n          schema:\n            type: string\n      responses:\n        '200':\n          description: Asset retrieved\n          content:\n            application/json:\n              schema:\n                $ref: '#/components/schemas/Asset'\n        '404':\n          description: Asset not found\n        '500':\n          description: Internal server error\n\ncomponents:\n  schemas:\n    Asset:\n      type: object\n      properties:\n        id:\n          type: string\n          example: \"asset123\"\n        name:\n          type: string\n          example: \"Laptop\"\n        type:\n          type: string\n          example: \"Hardware\"\n        location:\n          type: string\n          example: \"Bangalore\" 
  consumesApis:
    - csi-deployer
  implementsApis:
    - csi-intregation
  source:
    type: git
    target: https://github.com/ktx2kor/Backstage_test.git
    branch: bdc-develop
